--CLIAM INTIMATION CLIENT PORTAL 

select distinct LC.PLC_LOCADESC,count(CR_ID) as Branch_Wise_Claims_Intimate from hicl_changerequest CR
left outer join PR_GN_LC_LOCATION LC on LC.PLC_LOCACODE=CR.LOC_CODE
inner  join  HICL_USERs SU on Upper(CR.USERID)=Upper(SU.USERID)

where to_char(TO_DATE(CR_DATE, 'DD-MON-YYYY hh24:mi:ss'),'DD-MON-YYYY') between TO_DATE('01-JAN-2019') and TO_DATE('22-Apr-2019')
    AND    CR.BUSINESS_CLASS='NonCBD'  
        and 
         CR.CR_ID like 'CI%'
          group by LC.PLC_LOCADESC,CR.LOC_CODE;


-- CLAIM INTIMATION GIS 
SELECT distinct LC.POC_LOSSDESC , LOC.PLC_DESC,IH.gih_ITEM_DESC,BC.PBC_DESC,GIH_LOSSCLAIMED,GIH_LOSSASSESSED,GIH_LOSSADJUSTED
 ,IH.GIH_SUMINSURED,IH.GIH_BASICPREMIUM,IH.GIH_GROSSPREMIUM,IH.GIH_TOTAL_SI,
  IH.GDH_YEAR,IH.GIH_ITEMNO, 
  IH.GIH_ASSET_ITEMNO, IH.GIH_TOTAL_SI, IH.GIH_EFFECTIVE_DATE
 FROM GI_GC_IH_INTIMATIONHD  G
 left outer JOIN    GI_GU_IH_ITEM_HEADER IH On
         ( 
               IH.POR_ORG_CODE=G.POR_ORG_CODE
           AND IH.PLC_LOC_CODE =G.PLC_LOC_CODE  
           AND IH.PDP_DEPT_CODE= G.PDP_DEPT_CODE
           AND IH.PDT_DOCTYPE =G.PDT_DOCTYPE 
           AND IH.GDH_DOCUMENTNO =G.GIH_DOCUMENTNO  
           AND IH.GDH_YEAR = G.GIH_YEAR   
        ) 
        LEFT OUTER JOIN PR_GN_LC_LOCATION LOC ON LOC.PLC_LOC_CODE=G.PLC_LOC_CODE
         left outer join PR_GC_OC_LOSS_CAUSE LC on Lc.POC_LOSSCODE=G.POC_LOSSCODE
         left outer join PR_GG_BC_BUSINESS_CLASS BC on BC.PBC_BUSICLASS_CODE=G.PBC_BUSICLASS_CODE
LEFT OUTER JOIN GI_GU_ID_ITEM_DETAIL D

ON(IH.POR_ORG_CODE||IH.PLC_LOC_CODE||IH.PDP_DEPT_CODE||IH.PBC_BUSICLASS_CODE||IH.PIY_INSUTYPE||IH.PDT_DOCTYPE||IH.GDH_DOCUMENTNO||IH.GDH_RECORD_TYPE||IH.GDH_YEAR||IH.GIH_ITEMNO=

D.POR_ORG_CODE||D.PLC_LOC_CODE||D.PDP_DEPT_CODE||D.PBC_BUSICLASS_CODE||D.PIY_INSUTYPE||D.PDT_DOCTYPE||D.GDH_DOCUMENTNO||D.GDH_RECORD_TYPE||D.GDH_YEAR ||D.GIH_ITEMNO)
;
--GROUP BY A.PLC_DESC ;